language: python
python:
  - "2.7"
  # TODO: add this
  #- "3.4"

# cache ubuntu packages
cache: apt

  # command to install dependencies
before_install:
  - sudo apt-get install libhdf5-dev
install:
#  - "pip install -r requirements.txt"
  - pip install numpy
  - pip install h5py
#  - pip install scipy
  # - pip install --use-mirrors pyparsing
  - pip install --use-mirrors matplotlib
  - sudo -E ./travis_install.sh
#script: nosetests
script: nosetests simplelearn/
virtualenv:
  system_site_packages: true
# before_install:
#   - pip install python-dateutil
#   - pip install pytz
#   - sudo apt-get update -qq
#   - sudo apt-get install -qq libatlas-dev libatlas-base-dev liblapack-dev gfortran

# command to run tests
#script: nosetests simplelearn/