#! /usr/bin/env python

import argparse
import h5py
import numpy
import sys
from matplotlib import pyplot
from nose.tools import assert_equal


def parse_args():
    parser = argparse.ArgumentParser(
        description=("Plots a log file generated by simplelearn.training."
                     "EpochLogger"))

    parser.add_argument('-i',
                        '--input',
                        help='The log file.')

    parser.add_argument('--log',
                        action='store_true',
                        help='Use a logarithmic y axis.')

    return parser.parse_args()


def main():
    args = parse_args()

    h5_file = h5py.File(args.input, mode='r')
    logs = h5_file['logs']

    names = list(logs.iterkeys())
    names.sort()


    plot_args = []

    for name in names:
        data = logs[name]
        assert_equal(len(data.shape),
                     1,
                     "plot_log.py can only plot scalar values")

        plot_args.append(numpy.arange(len(data)))
        plot_args.append(data)

    axes = pyplot.gca()
    if args.log:
        axes.set_yscale('log')

    lines = axes.plot(*plot_args)  # pylint: disable=star-args
    axes.legend(lines, names)


    def on_key_press(event):
        if event.key == 'q':
            sys.exit(0)

    pyplot.gcf().canvas.mpl_connect('key_press_event', on_key_press)

    pyplot.show()

if __name__ == '__main__':
    main()
